"""empty message

Revision ID: 110776de86a5
Revises: 704794c0746c
Create Date: 2023-05-29 18:17:24.784203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110776de86a5'
down_revision = '704794c0746c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
