version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
#     networks:
#       - app

#   app:
#     build: .
#     depends_on:
#       - postgres
#     restart: always
#     ports:
#       - "8000:8000"c
#     networks:
#       - app

# networks:
#   app: