version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  app:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload"
    depends_on:
      - db
    networks:
      - app

networks:
  app: