version: '3.9'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data_task2:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - task2

  app:
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - "8000:8000"
    networks:
      - task2

networks:
  task2:
  
volumes:
  postgres_data_task2:
