openapi: 3.0.2
info:
  title: task1
  version: 0.1.0
paths:
  /question/:
    post:
      tags:
        - Question
      summary: Question
      operationId: question_question__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionNum'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Question Question  Post
                type: array
                items:
                  $ref: '#/components/schemas/Question'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Question:
      title: Question
      required:
        - question_id
        - question
        - answer
        - created_at
      type: object
      properties:
        question_id:
          title: Question Id
          type: integer
        question:
          title: Question
          type: string
        answer:
          title: Answer
          type: string
        created_at:
          title: Created At
          type: string
    QuestionNum:
      title: QuestionNum
      required:
        - question_num
      type: object
      properties:
        question_num:
          title: Question Num
          type: integer
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
